package com.preetamtech.Journal.entity;

import lombok.Data;
import lombok.NoArgsConstructor; // <--- Add this import
import lombok.NonNull;
import lombok.RequiredArgsConstructor; // <--- This is often generated by @NonNull, good to be aware

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "journal_entries")
@Data
@NoArgsConstructor // <--- Explicitly add a no-argument constructor
// @RequiredArgsConstructor // If you need a constructor with @NonNull fields, but @NoArgsConstructor is key for Jackson
public class JournalEntry {

    @Id
    private ObjectId id;

    @NonNull
    private String title;

    private String content;

}